#SPDX-License-Identifier: MIT-0
# handlers file for nagios-incus
---
# Restart Apache when Nagios web config changes
- name: restart apache
  service:
    name: apache2
    state: restarted
    enabled: true

# Restart Nagios Core
- name: restart nagios
  service:
    name: nagios
    state: restarted
    enabled: true

# Reload UFW if SNMP ports are added
- name: reload ufw
  command: ufw reload

# Restart SNMP service
- name: restart snmpd
  service:
    name: snmpd
    state: restarted
    enabled: true
